language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
# command to install dependencies
install:
  - pip install .
before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then flake8 figo; fi
script: nosetests
